# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

# First install & prepare the Dart SDK
- script: |
    sudo apt-get update
    sudo apt-get install apt-transport-https
    sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
    sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
    sudo apt-get update
    sudo apt-get install dart
    export PATH="$PATH":"$HOME/.pub-cache/bin"
    export PATH="$PATH":/usr/lib/dart/bin/
    pub global activate webdev
  displayName: 'Prepare Dart SDK'

# Compile the Dart code to JavaScript
- script: |
    export PATH="$PATH":"$HOME/.pub-cache/bin"
    export PATH="$PATH":/usr/lib/dart/bin/
    pub get
    webdev build
  displayName: 'Compile Dart Code'

# Download and extract the NW.js binaries
- script: |
    wget https://dl.nwjs.io/v0.40.0/nwjs-v0.40.0-win-x64.zip
  displayName: 'Download NW.js Windows'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.zip' 
    destinationFolder: nwjs_output/

# Copy the NW.js binaries to a archive directory
- script: |
    mkdir archive_path/
    cp nwjs_output/nwjs-v0.40.0-win-x64/nw.exe archive_path/
    cp nwjs_output/nwjs-v0.40.0-win-x64/nw_elf.dll archive_path/
    cp nwjs_output/nwjs-v0.40.0-win-x64/nw.dll archive_path/
    cp nwjs_output/nwjs-v0.40.0-win-x64/node.dll archive_path/
  displayName: 'Copy NW.js binaires to archive directory'

# Copy dart2js output to archive directory
- script: |
    cp package.json archive_path/
    cp -r build/* archive_path/
    cd archive_path
    tar -cf ../openrqm-client-desktop-nwjs.tar *
    cd ..
  displayName: 'Copy dart2js output to archive directory'

- task: GithubRelease@0 
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: benjaminSchilling33
    repositoryName: openrqm/openrqm-client-desktop-nwjs
    action: edit
    tagSource: manual
    tag: $(Build.SourceBranchName)  
    assetUploadMode: replace
    assets: |
         $(Build.Repository.LocalPath)/README.md
         $(Build.Repository.LocalPath)/openrqm-client-desktop-nwjs.tar
