# openrqm-client-desktop-nwjs
# Azure DevOps Pipeline for building the openrqm-client-desktop-nwjs project
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2019 Benjamin Schilling

trigger:
- master
- development

pool:
  vmImage: 'ubuntu-latest'

steps:

# First install & prepare the Dart SDK
- script: |
    sudo apt-get update
    sudo apt-get install apt-transport-https
    sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
    sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
    sudo apt-get update
    sudo apt-get install dart
    export PATH="$PATH":"$HOME/.pub-cache/bin"
    export PATH="$PATH":/usr/lib/dart/bin/
    pub global activate webdev
  displayName: 'Prepare Dart SDK'

# Compile the Dart code to JavaScript
- script: |
    export PATH="$PATH":"$HOME/.pub-cache/bin"
    export PATH="$PATH":/usr/lib/dart/bin/
    pub get
    webdev build
  displayName: 'Compile Dart Code'

# Download and extract the NW.js binaries
- script: |
    wget https://dl.nwjs.io/v0.40.0/nwjs-v0.40.0-win-x64.zip
  displayName: 'Download NW.js Windows'

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.zip' 
    destinationFolder: archive_path/

# Copy dart2js output to NW.js directory and tar the content
- script: |
    mkdir archive_path/nwjs-v0.40.0-win-x64/package.nw/
    cp package.json archive_path/nwjs-v0.40.0-win-x64/package.nw/
    cp -r build/* archive_path/nwjs-v0.40.0-win-x64/package.nw/
    cd archive_path/nwjs-v0.40.0-win-x64/
    ls -al
    tar -czf ../../openrqm-client-desktop-nwjs.tar.gz *
    ls -al
    cd ../..
    ls -al
  displayName: 'Copy dart2js output to archive directory'

# Convert Documentation to PDF
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    sudo apt-get install pandoc texlive
    pip install pandoc-plantuml-filter
  displayName: 'install required tools'


- script: |
    pandoc -o README.pdf README.md --filter pandoc-plantuml
    pandoc -o ARCHITECTURE.pdf doc/ARCHITECTURE.md --filter pandoc-plantuml
    pandoc -o WIREFRAME.pdf doc/WIREFRAME.md --filter pandoc-plantuml
    ls -al
  displayName: 'pandoc convert'

- script: |
    echo '##vso[task.setvariable variable=releasetag]release'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  displayName: 'Set Release Tag if master branch'

- script: |
    echo '##vso[task.setvariable variable=releasetag]development'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/development')
  displayName: 'Set Release Tag if development branch'

- task: GithubRelease@0 
  condition: or(and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master')), and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development')))
  displayName: 'Create GitHub Release'      
  inputs:
    gitHubConnection: benjaminSchilling33
    repositoryName: openrqm/openrqm-client-desktop-nwjs
    action: edit
    tagSource: manual
    tag: $(releasetag) 
    assetUploadMode: replace
    assets: |
         $(Build.Repository.LocalPath)/README.pdf
         $(Build.Repository.LocalPath)/doc/ARCHITECTURE.pdf
         $(Build.Repository.LocalPath)/doc/WIREFRAME.pdf
         $(Build.Repository.LocalPath)/openrqm-client-desktop-nwjs.tar.gz
