name: openrqm_client_desktop_nwjs
description: The OpenRQM client reference implementation
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0+1
  angular_router: ^2.0.0-alpha
  bootjack:
  slickdart: ^0.2.0+4
  openrqm: ^1.0.4

dev_dependencies:
  build_runner: ^1.5.1
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
